# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Eom Dongyeon\Documents\GitHub\2017-Scripts\엄동연\2017_script_termProject\detailPopup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(882, 416)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        Dialog.setFont(font)
        self.webView = QtWebKit.QWebView(Dialog)
        self.webView.setGeometry(QtCore.QRect(30, 80, 341, 221))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("http://www.animal.go.kr/files/shelter/2017/05/201705311005791.jpg")))
        self.webView.setZoomFactor(1.0)
        self.webView.setObjectName(_fromUtf8("webView"))
        self.noticeNoLabel = QtGui.QLabel(Dialog)
        self.noticeNoLabel.setGeometry(QtCore.QRect(30, 30, 311, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.noticeNoLabel.setFont(font)
        self.noticeNoLabel.setObjectName(_fromUtf8("noticeNoLabel"))
        self.KindCdLabel = QtGui.QLabel(Dialog)
        self.KindCdLabel.setGeometry(QtCore.QRect(30, 330, 191, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.KindCdLabel.setFont(font)
        self.KindCdLabel.setObjectName(_fromUtf8("KindCdLabel"))
        self.sexCdLabel = QtGui.QLabel(Dialog)
        self.sexCdLabel.setGeometry(QtCore.QRect(230, 330, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.sexCdLabel.setFont(font)
        self.sexCdLabel.setObjectName(_fromUtf8("sexCdLabel"))
        self.ageLabel = QtGui.QLabel(Dialog)
        self.ageLabel.setGeometry(QtCore.QRect(330, 330, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName(_fromUtf8("ageLabel"))
        self.colorCdLabel = QtGui.QLabel(Dialog)
        self.colorCdLabel.setGeometry(QtCore.QRect(610, 330, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.colorCdLabel.setFont(font)
        self.colorCdLabel.setObjectName(_fromUtf8("colorCdLabel"))
        self.neuterYnLabel = QtGui.QLabel(Dialog)
        self.neuterYnLabel.setGeometry(QtCore.QRect(470, 330, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.neuterYnLabel.setFont(font)
        self.neuterYnLabel.setObjectName(_fromUtf8("neuterYnLabel"))
        self.specialMarkLabel = QtGui.QLabel(Dialog)
        self.specialMarkLabel.setGeometry(QtCore.QRect(30, 370, 441, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.specialMarkLabel.setFont(font)
        self.specialMarkLabel.setObjectName(_fromUtf8("specialMarkLabel"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(710, 330, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.happenPlaceLabel = QtGui.QLabel(Dialog)
        self.happenPlaceLabel.setGeometry(QtCore.QRect(410, 90, 331, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.happenPlaceLabel.setFont(font)
        self.happenPlaceLabel.setObjectName(_fromUtf8("happenPlaceLabel"))
        self.careNmLabel = QtGui.QLabel(Dialog)
        self.careNmLabel.setGeometry(QtCore.QRect(410, 120, 311, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.careNmLabel.setFont(font)
        self.careNmLabel.setObjectName(_fromUtf8("careNmLabel"))
        self.careAddrLabel = QtGui.QLabel(Dialog)
        self.careAddrLabel.setGeometry(QtCore.QRect(410, 150, 441, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.careAddrLabel.setFont(font)
        self.careAddrLabel.setObjectName(_fromUtf8("careAddrLabel"))
        self.careTelLabel = QtGui.QLabel(Dialog)
        self.careTelLabel.setGeometry(QtCore.QRect(410, 180, 341, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.careTelLabel.setFont(font)
        self.careTelLabel.setObjectName(_fromUtf8("careTelLabel"))
        self.chargeNameLabel = QtGui.QLabel(Dialog)
        self.chargeNameLabel.setGeometry(QtCore.QRect(410, 210, 341, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.chargeNameLabel.setFont(font)
        self.chargeNameLabel.setObjectName(_fromUtf8("chargeNameLabel"))
        self.officetelLabel = QtGui.QLabel(Dialog)
        self.officetelLabel.setGeometry(QtCore.QRect(410, 240, 341, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.officetelLabel.setFont(font)
        self.officetelLabel.setObjectName(_fromUtf8("officetelLabel"))
        self.orgNmLabel = QtGui.QLabel(Dialog)
        self.orgNmLabel.setGeometry(QtCore.QRect(410, 270, 341, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(9)
        self.orgNmLabel.setFont(font)
        self.orgNmLabel.setObjectName(_fromUtf8("orgNmLabel"))
        self.desertionNoLabel = QtGui.QLabel(Dialog)
        self.desertionNoLabel.setGeometry(QtCore.QRect(410, 30, 331, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.desertionNoLabel.setFont(font)
        self.desertionNoLabel.setObjectName(_fromUtf8("desertionNoLabel"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(710, 30, 141, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.sendMailPushButton = QtGui.QPushButton(Dialog)
        self.sendMailPushButton.setGeometry(QtCore.QRect(720, 370, 131, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        self.sendMailPushButton.setFont(font)
        self.sendMailPushButton.setCheckable(True)
        self.sendMailPushButton.setObjectName(_fromUtf8("sendMailPushButton"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 50, 841, 16))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(20, 310, 841, 16))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.MapPushButton = QtGui.QPushButton(Dialog)
        self.MapPushButton.setGeometry(QtCore.QRect(750, 180, 101, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        self.MapPushButton.setFont(font)
        self.MapPushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.MapPushButton.setCheckable(True)
        self.MapPushButton.setObjectName(_fromUtf8("MapPushButton"))
        self.sendMailLineEdit = QtGui.QLineEdit(Dialog)
        self.sendMailLineEdit.setGeometry(QtCore.QRect(500, 370, 211, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("맑은 고딕"))
        self.sendMailLineEdit.setFont(font)
        self.sendMailLineEdit.setObjectName(_fromUtf8("sendMailLineEdit"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.noticeNoLabel.setText(_translate("Dialog", "공고번호: 12345675", None))
        self.KindCdLabel.setText(_translate("Dialog", "품종: 고양이", None))
        self.sexCdLabel.setText(_translate("Dialog", "성별:  M", None))
        self.ageLabel.setText(_translate("Dialog", "나이: 2017(년생)", None))
        self.colorCdLabel.setText(_translate("Dialog", "색상: 검/흰", None))
        self.neuterYnLabel.setText(_translate("Dialog", "중성화 여부: U", None))
        self.specialMarkLabel.setText(_translate("Dialog", "특징: 활발함", None))
        self.label_8.setText(_translate("Dialog", "체중: 0.5(kg)", None))
        self.happenPlaceLabel.setText(_translate("Dialog", "발견장소: 연수구청", None))
        self.careNmLabel.setText(_translate("Dialog", "보호소 이름: 인천광역시수의사회", None))
        self.careAddrLabel.setText(_translate("Dialog", "보호주소: 인천광역시 계약구 다남로165번길 56(다남동, 유기동물 보호소)", None))
        self.careTelLabel.setText(_translate("Dialog", "보호소 전화번호:  123-123-1234", None))
        self.chargeNameLabel.setText(_translate("Dialog", "담당자: 원구연", None))
        self.officetelLabel.setText(_translate("Dialog", "담당자 연락처: 010-000-0000", None))
        self.orgNmLabel.setText(_translate("Dialog", "관할기관: 인천연수구", None))
        self.desertionNoLabel.setText(_translate("Dialog", "유기번호 :  12345", None))
        self.label_17.setText(_translate("Dialog", "접수일: 20170530", None))
        self.sendMailPushButton.setText(_translate("Dialog", "정보 메일보내기", None))
        self.MapPushButton.setText(_translate("Dialog", "지도보기", None))
        self.sendMailLineEdit.setText(_translate("Dialog", "수신자 이메일", None))

from PyQt4 import QtWebKit
